rules:
  - name: "Protect main branch"
    branches: ["main", "master"]
    required_status_checks:
      strict: true
      contexts:
        - "CI / Build and Test"
    #required_pull_request_reviews:
      #required_approving_review_count: 1
      #dismiss_stale_reviews: true
      #require_code_owner_reviews: false
    restrictions: null
    enforce_admins: true
    allow_force_pushes: false
    allow_deletions: false