services:
  manager_db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: "pg_isready -U ${DB_USER} -d ${DB_NAME}"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15432:5432"
  manager_project:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      manager_db:
        condition: service_healthy
    ports:
      - "8989:8989"